/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author rob_a
 */
public class Calendario extends javax.swing.JFrame {
    
private FondoVentana fondo;

    public Calendario() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo1.png"));
        setIconImage(icon);       
        fondo = new FondoVentana();
        this.add(fondo);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
   
        });
        
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e){
                  int x, y;
                  x = Calendario.this.getWidth();
                  y = Calendario.this.getHeight();
                  fondo.fondoZize(x, y);
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCalendario = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        lblDivision = new javax.swing.JLabel();
        cbDivision = new javax.swing.JComboBox<>();
        lblJornada = new javax.swing.JLabel();
        cbJornada = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnFiltroEditar = new javax.swing.JButton();
        btnFiltroAplicar = new javax.swing.JButton();
        pGestionFechas = new javax.swing.JPanel();
        jInicioCalendario = new javax.swing.JPanel();
        lbInicioFechaInicio = new javax.swing.JLabel();
        txtInicioFechaInicio = new javax.swing.JTextField();
        lblInicioFechaFin = new javax.swing.JLabel();
        txtInicioFechaFin = new javax.swing.JTextField();
        btnIniciocEditar = new javax.swing.JButton();
        btnInicioAceptar = new javax.swing.JButton();
        jExcluirFechas = new javax.swing.JPanel();
        lbExcFechaInicio = new javax.swing.JLabel();
        txtExcFechaInicio = new javax.swing.JTextField();
        lblExcFechaFin = new javax.swing.JLabel();
        txtExcFechaFin = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        cbDescripcion = new javax.swing.JComboBox<>();
        btnExcEditar = new javax.swing.JButton();
        btnExcExcluir = new javax.swing.JButton();
        scrollCalendario = new javax.swing.JScrollPane();
        tCalendario = new javax.swing.JTable();
        btnCalendarioEditar = new javax.swing.JButton();
        btnCalendarioGenerar = new javax.swing.JButton();
        btnCalendarioSalir = new javax.swing.JButton();
        mbCalendario = new javax.swing.JMenuBar();
        mExportar = new javax.swing.JMenu();
        miExcel = new javax.swing.JMenuItem();
        miPDF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Generación de Calendario");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        pCalendario.setBackground(new java.awt.Color(255, 255, 255));
        pCalendario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 4, true), "  GESTIONAR FILTROS DE EXPORTACIÓN  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(31, 87, 12))); // NOI18N
        pCalendario.setPreferredSize(new java.awt.Dimension(1366, 105));

        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCategoria.setText("Categoría");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Senior", "Veteranos+30", "Veteranos+35" }));
        cbCategoria.setEnabled(false);

        lblDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDivision.setText("División");

        cbDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primera", "Segunda", "Tercera" }));
        cbDivision.setEnabled(false);
        cbDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisionActionPerformed(evt);
            }
        });

        lblJornada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblJornada.setText("Jornada");

        cbJornada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cbJornada.setEnabled(false);

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaInicio.setText("Fecha de Incio");

        txtFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaInicio.setEnabled(false);
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaFin.setText("Fecha de Fin");

        txtFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaFin.setEnabled(false);
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });

        btnFiltroEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnFiltroEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltroEditar.setText("Editar Filtros");
        btnFiltroEditar.setFocusPainted(false);
        btnFiltroEditar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnFiltroEditar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnFiltroEditar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnFiltroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroEditarActionPerformed(evt);
            }
        });

        btnFiltroAplicar.setBackground(new java.awt.Color(31, 87, 12));
        btnFiltroAplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltroAplicar.setText("Aplicar Filtros");
        btnFiltroAplicar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnFiltroAplicar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnFiltroAplicar.setName(""); // NOI18N
        btnFiltroAplicar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnFiltroAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCalendarioLayout = new javax.swing.GroupLayout(pCalendario);
        pCalendario.setLayout(pCalendarioLayout);
        pCalendarioLayout.setHorizontalGroup(
            pCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCalendarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDivision)
                .addGap(18, 18, 18)
                .addComponent(cbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJornada)
                .addGap(18, 18, 18)
                .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaInicio)
                .addGap(18, 18, 18)
                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaFin)
                .addGap(18, 18, 18)
                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnFiltroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltroAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pCalendarioLayout.setVerticalGroup(
            pCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivision)
                    .addComponent(cbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJornada)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pGestionFechas.setBackground(new java.awt.Color(255, 255, 255));
        pGestionFechas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 4, true), "  EXCLUIR FECHAS DEL CALENDARIO  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(31, 87, 12))); // NOI18N
        pGestionFechas.setPreferredSize(new java.awt.Dimension(1366, 105));

        jInicioCalendario.setBackground(new java.awt.Color(255, 255, 255));
        jInicioCalendario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), " FECHA DE INICIO DE CALENDARIO ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(31, 87, 12)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(31, 87, 12))); // NOI18N
        jInicioCalendario.setPreferredSize(new java.awt.Dimension(978, 67));

        lbInicioFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        lbInicioFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbInicioFechaInicio.setText("Fecha de Incio de Calendario");

        txtInicioFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInicioFechaInicio.setEnabled(false);
        txtInicioFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioFechaInicioActionPerformed(evt);
            }
        });

        lblInicioFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        lblInicioFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicioFechaFin.setText("Fecha de Fin de Calendario");

        txtInicioFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInicioFechaFin.setEnabled(false);
        txtInicioFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioFechaFinActionPerformed(evt);
            }
        });

        btnIniciocEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnIniciocEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciocEditar.setText("Editar");
        btnIniciocEditar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnIniciocEditar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnIniciocEditar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnIniciocEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciocEditarActionPerformed(evt);
            }
        });

        btnInicioAceptar.setBackground(new java.awt.Color(31, 87, 12));
        btnInicioAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioAceptar.setText("Aceptar");
        btnInicioAceptar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnInicioAceptar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnInicioAceptar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnInicioAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInicioCalendarioLayout = new javax.swing.GroupLayout(jInicioCalendario);
        jInicioCalendario.setLayout(jInicioCalendarioLayout);
        jInicioCalendarioLayout.setHorizontalGroup(
            jInicioCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInicioFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInicioFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInicioFechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInicioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciocEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicioAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInicioCalendarioLayout.setVerticalGroup(
            jInicioCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioCalendarioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jInicioCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInicioFechaInicio)
                    .addComponent(txtInicioFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInicioFechaFin)
                    .addComponent(txtInicioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciocEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicioAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jExcluirFechas.setBackground(new java.awt.Color(255, 255, 255));
        jExcluirFechas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)), "  EXCLUIR FECHAS DEL CALENDARIO  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(31, 87, 12))); // NOI18N

        lbExcFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        lbExcFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbExcFechaInicio.setText("Fecha de Incio");

        txtExcFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtExcFechaInicio.setEnabled(false);
        txtExcFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExcFechaInicioActionPerformed(evt);
            }
        });

        lblExcFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        lblExcFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExcFechaFin.setText("Fecha de Fin");

        txtExcFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtExcFechaFin.setEnabled(false);
        txtExcFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExcFechaFinActionPerformed(evt);
            }
        });

        lblDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescripcion.setText("Descripción");

        cbDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDescripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un motivo", "Periodo hábil", "Fiesta nacional", "Fiesta local", "Periodo vacacional", "Otros" }));
        cbDescripcion.setEnabled(false);

        btnExcEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnExcEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnExcEditar.setText("Editar Fechas");
        btnExcEditar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnExcEditar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnExcEditar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnExcEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcEditarActionPerformed(evt);
            }
        });

        btnExcExcluir.setBackground(new java.awt.Color(31, 87, 12));
        btnExcExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcExcluir.setText("Excluir Fechas");
        btnExcExcluir.setMaximumSize(new java.awt.Dimension(120, 23));
        btnExcExcluir.setMinimumSize(new java.awt.Dimension(120, 23));
        btnExcExcluir.setPreferredSize(new java.awt.Dimension(120, 23));
        btnExcExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jExcluirFechasLayout = new javax.swing.GroupLayout(jExcluirFechas);
        jExcluirFechas.setLayout(jExcluirFechasLayout);
        jExcluirFechasLayout.setHorizontalGroup(
            jExcluirFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jExcluirFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbExcFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtExcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExcFechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtExcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addGap(18, 18, 18)
                .addComponent(cbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jExcluirFechasLayout.setVerticalGroup(
            jExcluirFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jExcluirFechasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jExcluirFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExcFechaInicio)
                    .addComponent(txtExcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExcFechaFin)
                    .addComponent(txtExcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion)
                    .addComponent(btnExcEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pGestionFechasLayout = new javax.swing.GroupLayout(pGestionFechas);
        pGestionFechas.setLayout(pGestionFechasLayout);
        pGestionFechasLayout.setHorizontalGroup(
            pGestionFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGestionFechasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGestionFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jExcluirFechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jInicioCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 1310, Short.MAX_VALUE))
                .addContainerGap())
        );
        pGestionFechasLayout.setVerticalGroup(
            pGestionFechasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pGestionFechasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jInicioCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jExcluirFechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tCalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Jornada", "Fecha", "Día", "Hora", "Equipo Local", "Equipo Visitante", "Campo", "Competición", "Partido aplazado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tCalendario.setEnabled(false);
        scrollCalendario.setViewportView(tCalendario);

        btnCalendarioEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnCalendarioEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendarioEditar.setText("Editar Calendario");
        btnCalendarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioEditarActionPerformed(evt);
            }
        });

        btnCalendarioGenerar.setBackground(new java.awt.Color(31, 87, 12));
        btnCalendarioGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendarioGenerar.setText("Guardar Calendario");
        btnCalendarioGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioGenerarActionPerformed(evt);
            }
        });

        btnCalendarioSalir.setBackground(new java.awt.Color(31, 87, 12));
        btnCalendarioSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendarioSalir.setText("Salir");
        btnCalendarioSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioSalirActionPerformed(evt);
            }
        });

        mbCalendario.setBackground(new java.awt.Color(31, 87, 12));
        mbCalendario.setForeground(new java.awt.Color(255, 255, 255));

        mExportar.setForeground(new java.awt.Color(255, 255, 255));
        mExportar.setText("Exportar Calendario");
        mExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExportarActionPerformed(evt);
            }
        });

        miExcel.setBackground(new java.awt.Color(31, 87, 12));
        miExcel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miExcel.setForeground(new java.awt.Color(255, 255, 255));
        miExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/excel.png"))); // NOI18N
        miExcel.setText("Exportar como Excel");
        miExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcelActionPerformed(evt);
            }
        });
        mExportar.add(miExcel);

        miPDF.setBackground(new java.awt.Color(31, 87, 12));
        miPDF.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miPDF.setForeground(new java.awt.Color(255, 255, 255));
        miPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pdf.png"))); // NOI18N
        miPDF.setText("Exportar como PDF");
        miPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPDFActionPerformed(evt);
            }
        });
        mExportar.add(miPDF);

        mbCalendario.add(mExportar);

        setJMenuBar(mbCalendario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalendarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalendarioGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalendarioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollCalendario)
                    .addComponent(pGestionFechas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                    .addComponent(pCalendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pGestionFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalendarioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalendarioGenerar)
                    .addComponent(btnCalendarioEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalendarioGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioGenerarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/guardar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios realizados en el calendario?\n"
                + "                    Esta acción no se puede deshacer", "Guardar cambios", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                
        }      
        
    }//GEN-LAST:event_btnCalendarioGenerarActionPerformed

    private void mExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mExportarActionPerformed

    private void miExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcelActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Excel (*.xls; *.xlsx)", "xls", "xlsx");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showSaveDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File fichero = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fichero.getAbsolutePath());
            //aqui debe coger los datos de la BBDD y guardarlos en un excel

        }
//        String categoria2 = (String) cbCategoria.getSelectedItem();
//        String division2 = (String) cbDivision.getSelectedItem();
//        String jornada2 = (String) cbJornada.getSelectedItem();
//        
//        switch(categoria2) {
//            
//          case "Todas": 
//            switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioTODAS.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//            
//        case "Senior": 
//            switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioSenior.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//        case "Veteranos+30": 
//                switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+30.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        case "Veteranos+35": 
//            switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+35.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        }  
    }//GEN-LAST:event_miExcelActionPerformed

    private void miPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPDFActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo PDF (*.pdf)", "pdf");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showSaveDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File fichero = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fichero.getAbsolutePath());
            //aqui debe coger los datos de la BBDD y guardarlos en un PDF

        }
//        String categoria = (String) cbCategoria.getSelectedItem();
//        String division = (String) cbDivision.getSelectedItem();
//        String jornada = (String) cbJornada.getSelectedItem();
//        
//        switch(categoria) {
//            
//        case "Todas": 
//            switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioTODAS.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//            
//        case "Senior": 
//            switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioSenior.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//        case "Veteranos+30": 
//                switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+30.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        case "Veteranos+35": 
//            switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+35.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        }
    }//GEN-LAST:event_miPDFActionPerformed

    private void txtInicioFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioFechaInicioActionPerformed

    private void txtInicioFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioFechaFinActionPerformed

    private void btnIniciocEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciocEditarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/editar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea editar la fecha de inicio y fin del calendario?", "Editar Fechas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
            txtInicioFechaInicio.setEnabled(true);
            txtInicioFechaFin.setEnabled(true);
            }
    }//GEN-LAST:event_btnIniciocEditarActionPerformed

    private void btnFiltroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroEditarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/editar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea editar los filtros del calendario?", "Editar Filtros", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
            cbCategoria.setEnabled(true);
            cbDivision.setEnabled(true);
            cbJornada.setEnabled(true);
            txtFechaInicio.setEnabled(true);
            txtFechaFin.setEnabled(true);
        }
    }//GEN-LAST:event_btnFiltroEditarActionPerformed

    private void btnFiltroAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroAplicarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/aceptar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea aplicar los filtros seleccionados?", "Aplicar Filtros", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                
        }
    }//GEN-LAST:event_btnFiltroAplicarActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void cbDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDivisionActionPerformed

    private void btnInicioAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioAceptarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/aceptar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea aplicar los cambios en las fechas de inicio y fin del calendario?\n "
               + "                       Esta acción no se puede deshacer", "Aceptar cambios",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                
        }
    }//GEN-LAST:event_btnInicioAceptarActionPerformed

    private void btnCalendarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioEditarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/editar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea editar los datos del calendario?", "Editar datos del calendario", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
            tCalendario.setEnabled(true);
        }
    }//GEN-LAST:event_btnCalendarioEditarActionPerformed

    private void btnCalendarioSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioSalirActionPerformed
        close();            
    }//GEN-LAST:event_btnCalendarioSalirActionPerformed

    private void txtExcFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExcFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExcFechaInicioActionPerformed

    private void txtExcFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExcFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExcFechaFinActionPerformed

    private void btnExcEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcEditarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/editar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea editar las fechas de exclusión en el calendario?", "Editar Fechas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
            txtExcFechaInicio.setEnabled(true);
            txtExcFechaFin.setEnabled(true);
            cbDescripcion.setEnabled(true);
            }
    }//GEN-LAST:event_btnExcEditarActionPerformed

    private void btnExcExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcExcluirActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/aceptar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea excluir las fechas seleccionadas?\n "
                + "      Esta acción no se puede deshacer", "Excluir Fechas", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                
        }
    }//GEN-LAST:event_btnExcExcluirActionPerformed
    
    public void close() {
        ImageIcon icon = new ImageIcon("src/resources/back.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea salir de 'Generar calendario'?", "Salir de 'Generar calendario'", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
            if (input == JOptionPane.YES_OPTION) {
             dispose();             
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendarioEditar;
    private javax.swing.JButton btnCalendarioGenerar;
    private javax.swing.JButton btnCalendarioSalir;
    private javax.swing.JButton btnExcEditar;
    private javax.swing.JButton btnExcExcluir;
    private javax.swing.JButton btnFiltroAplicar;
    private javax.swing.JButton btnFiltroEditar;
    private javax.swing.JButton btnInicioAceptar;
    private javax.swing.JButton btnIniciocEditar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbDescripcion;
    private javax.swing.JComboBox<String> cbDivision;
    private javax.swing.JComboBox<String> cbJornada;
    private javax.swing.JPanel jExcluirFechas;
    private javax.swing.JPanel jInicioCalendario;
    private javax.swing.JLabel lbExcFechaInicio;
    private javax.swing.JLabel lbInicioFechaInicio;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblExcFechaFin;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblInicioFechaFin;
    private javax.swing.JLabel lblJornada;
    private javax.swing.JMenu mExportar;
    private javax.swing.JMenuBar mbCalendario;
    private javax.swing.JMenuItem miExcel;
    private javax.swing.JMenuItem miPDF;
    private javax.swing.JPanel pCalendario;
    private javax.swing.JPanel pGestionFechas;
    private javax.swing.JScrollPane scrollCalendario;
    private javax.swing.JTable tCalendario;
    private javax.swing.JTextField txtExcFechaFin;
    private javax.swing.JTextField txtExcFechaInicio;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtInicioFechaFin;
    private javax.swing.JTextField txtInicioFechaInicio;
    // End of variables declaration//GEN-END:variables
}
