/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sources.GestionarCampos;

/**
 *
 * @author rob_a
 */
public class AgregarCampo extends javax.swing.JDialog {
    GestionarCampos gc = new GestionarCampos();

    /**
     * Creates new form EditarCampo
     */
    public AgregarCampo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(232, 245, 228));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoAgregarCampo = new javax.swing.JLabel();
        txtAgregarCampo = new javax.swing.JTextField();
        btnAgregarCampo = new javax.swing.JButton();
        btnCancelarCampo = new javax.swing.JButton();
        lblAgreagarCampo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar campo");
        setBackground(new java.awt.Color(0, 0, 0));

        lblLogoAgregarCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/campo_menu.png"))); // NOI18N

        btnAgregarCampo.setBackground(new java.awt.Color(31, 87, 12));
        btnAgregarCampo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCampo.setText("Aceptar");
        btnAgregarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCampoActionPerformed(evt);
            }
        });

        btnCancelarCampo.setBackground(new java.awt.Color(31, 87, 12));
        btnCancelarCampo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCampo.setText("Cancelar");
        btnCancelarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCampoActionPerformed(evt);
            }
        });

        lblAgreagarCampo.setBackground(new java.awt.Color(31, 87, 12));
        lblAgreagarCampo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblAgreagarCampo.setForeground(new java.awt.Color(31, 87, 12));
        lblAgreagarCampo.setText("Agregar campo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogoAgregarCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAgreagarCampo)
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addComponent(txtAgregarCampo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogoAgregarCampo)
                    .addComponent(lblAgreagarCampo))
                .addGap(18, 18, 18)
                .addComponent(txtAgregarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCampo)
                    .addComponent(btnAgregarCampo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCampoActionPerformed
            String campo= txtAgregarCampo.getText();
            if (txtAgregarCampo.getText().equals("")){
                ImageIcon icon = new ImageIcon(getClass().getResource("/resources/warning.png"));
                JOptionPane.showMessageDialog(rootPane, "Debe escribir el nombre de un campo","Nombre del campo", JOptionPane.QUESTION_MESSAGE, icon);
            }else{
                try {
                    gc.guardarCampo(campo);
                } catch (SQLException ex) {
                    Logger.getLogger(AgregarCampo.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
        
    }//GEN-LAST:event_btnAgregarCampoActionPerformed

    private void btnCancelarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCampoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarCampo dialog = new AgregarCampo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCampo;
    private javax.swing.JButton btnCancelarCampo;
    private javax.swing.JLabel lblAgreagarCampo;
    private javax.swing.JLabel lblLogoAgregarCampo;
    private javax.swing.JTextField txtAgregarCampo;
    // End of variables declaration//GEN-END:variables
}
