/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sources.ActualizarDatosAplazados;
import sources.GestionarCampeonato;
import sources.MostrarDatos;


/**
 *
 * @author rob_a
 */
public class Aplazados extends javax.swing.JFrame {
    
private FondoVentana fondo;
private final MostrarDatos md = new MostrarDatos();
private final GestionarCampeonato gc = new GestionarCampeonato  ();

    public Aplazados() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Image icon = Toolkit.getDefaultToolkit().getImage("logo.png");
        setIconImage(icon);       
        fondo = new FondoVentana();
        this.add(fondo);
        
        tAplazados.getColumnModel().getColumn(0).setPreferredWidth(50);
        tAplazados.getColumnModel().getColumn(1).setPreferredWidth(75);
        tAplazados.getColumnModel().getColumn(2).setPreferredWidth(120);
        tAplazados.getColumnModel().getColumn(3).setPreferredWidth(120);
        tAplazados.getColumnModel().getColumn(4).setPreferredWidth(120);
        tAplazados.getColumnModel().getColumn(5).setPreferredWidth(325);
        tAplazados.getColumnModel().getColumn(6).setPreferredWidth(325);
        tAplazados.getColumnModel().getColumn(7).setPreferredWidth(390);
        tAplazados.getColumnModel().getColumn(8).setPreferredWidth(370);
 //       tAplazados.getColumnModel().getColumn(9).setPreferredWidth(120);
        md.llenarTAplazados(this.tAplazados);
        
        ActualizarDatosAplazados ada = new ActualizarDatosAplazados(this.tAplazados);
        tAplazados.getModel().addTableModelListener(ada);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
   
        });
        
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e){
                  int x, y;
                  x = Aplazados.this.getWidth();
                  y = Aplazados.this.getHeight();
                  fondo.fondoZize(x, y);
            }
        });  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollAplazados = new javax.swing.JScrollPane();
        tAplazados = new javax.swing.JTable();
        btnAnadirAplazados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Partidos aplazados");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        tAplazados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jornada", "Fecha", "Día", "Hora", "Equipo Local", "Equipo Visitante", "Campo", "Competición"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tAplazados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tAplazados.getTableHeader().setReorderingAllowed(false);
        scrollAplazados.setViewportView(tAplazados);

        btnAnadirAplazados.setBackground(new java.awt.Color(31, 87, 12));
        btnAnadirAplazados.setForeground(new java.awt.Color(255, 255, 255));
        btnAnadirAplazados.setText("Añadir partido");
        btnAnadirAplazados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirAplazadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAplazados, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnadirAplazados, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollAplazados, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAnadirAplazados)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirAplazadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirAplazadosActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/guardar.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea añadir el partido aplazado a la jornada?", "Añadir partido aplazado", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
               
            DefaultTableModel model = (DefaultTableModel) tAplazados.getModel();
            int[] rows = tAplazados.getSelectedRows();
            int filsel = tAplazados.getSelectedRow();
            if(filsel == -1){
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una fila","Seleccione una  fila de la tabla", JOptionPane.QUESTION_MESSAGE, icon);
            }else{
                try {
                    for(int i=0;i<rows.length;i++){
                        int id = (int) model.getValueAt(filsel, 0);
//                        String fecha = (String) model.getValueAt(filsel, 2);
                        String fecha = "2017-08-28";
                        String hora = (String) model.getValueAt(filsel, 4);
                        String campo = (String) model.getValueAt(filsel, 7);
                        
                        System.out.println(id);
                        System.out.println(fecha);
                        System.out.println(hora);
                        System.out.println(campo);
                        gc.actualizarAplazados (id, fecha, hora, campo);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        
    }//GEN-LAST:event_btnAnadirAplazadosActionPerformed

        public void close() {
             dispose();             
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirAplazados;
    private javax.swing.JScrollPane scrollAplazados;
    private javax.swing.JTable tAplazados;
    // End of variables declaration//GEN-END:variables
}
