/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sources.Filtros;
import sources.GeneraCalendario;
import sources.MostrarDatos;

/**
 *
 * @author rob_a
 */
public class Calendario extends javax.swing.JFrame {
    
private FondoVentana fondo;
private final MostrarDatos md = new MostrarDatos();
private final GeneraCalendario gc = new GeneraCalendario();
private Filtros filtro;

    public Calendario() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo1.png"));
        setIconImage(icon);       
        fondo = new FondoVentana();
        this.add(fondo);
        
        md.llenarComboCategorias(this.cbCategoria);
        md.llenarComboDivisiones(this.cbDivision);
        md.llenarComboJornadas(this.cbJornada);
        md.llenarTCalendario(this.tCalendario);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
   
        });
        
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e){
                  int x, y;
                  x = Calendario.this.getWidth();
                  y = Calendario.this.getHeight();
                  fondo.fondoZize(x, y);
            }
        });   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInicioCalendario = new javax.swing.JPanel();
        lbInicioFechaInicio = new javax.swing.JLabel();
        txtInicioFechaInicio = new javax.swing.JTextField();
        lblInicioFechaFin = new javax.swing.JLabel();
        txtInicioFechaFin = new javax.swing.JTextField();
        btnIniciocEditar = new javax.swing.JButton();
        btnInicioAplicar = new javax.swing.JButton();
        pCalendario = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        lblDivision = new javax.swing.JLabel();
        cbDivision = new javax.swing.JComboBox<>();
        lblJornada = new javax.swing.JLabel();
        cbJornada = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        btnFiltroEditar = new javax.swing.JButton();
        btnFiltroAceptar = new javax.swing.JButton();
        scrollCalendario = new javax.swing.JScrollPane();
        tCalendario = new javax.swing.JTable();
        btnCalendarioEditar = new javax.swing.JButton();
        btnCalendarioGenerar = new javax.swing.JButton();
        btnCalendarioSalir = new javax.swing.JButton();
        mbCalendario = new javax.swing.JMenuBar();
        mExportar = new javax.swing.JMenu();
        miExcel = new javax.swing.JMenuItem();
        miPDF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Generación de Calendario");
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));

        jInicioCalendario.setBackground(new java.awt.Color(255, 255, 255));
        jInicioCalendario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 4, true), "  FECHA DE INICIO DE CALENDARIO  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(31, 87, 12)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(31, 87, 12))); // NOI18N
        jInicioCalendario.setPreferredSize(new java.awt.Dimension(978, 67));

        lbInicioFechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        lbInicioFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbInicioFechaInicio.setText("Fecha de Incio de Calendario");

        txtInicioFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInicioFechaInicio.setEnabled(false);
        txtInicioFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioFechaInicioActionPerformed(evt);
            }
        });

        lblInicioFechaFin.setBackground(new java.awt.Color(255, 255, 255));
        lblInicioFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInicioFechaFin.setText("Fecha de Fin de Calendario");

        txtInicioFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInicioFechaFin.setEnabled(false);
        txtInicioFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInicioFechaFinActionPerformed(evt);
            }
        });

        btnIniciocEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnIniciocEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciocEditar.setText("Editar fecha");
        btnIniciocEditar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnIniciocEditar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnIniciocEditar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnIniciocEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciocEditarActionPerformed(evt);
            }
        });

        btnInicioAplicar.setBackground(new java.awt.Color(31, 87, 12));
        btnInicioAplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioAplicar.setText("Aceptar");
        btnInicioAplicar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnInicioAplicar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnInicioAplicar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnInicioAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInicioCalendarioLayout = new javax.swing.GroupLayout(jInicioCalendario);
        jInicioCalendario.setLayout(jInicioCalendarioLayout);
        jInicioCalendarioLayout.setHorizontalGroup(
            jInicioCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInicioFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInicioFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInicioFechaFin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInicioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addComponent(btnIniciocEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicioAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInicioCalendarioLayout.setVerticalGroup(
            jInicioCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioCalendarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInicioCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbInicioFechaInicio)
                    .addComponent(txtInicioFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInicioFechaFin)
                    .addComponent(txtInicioFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciocEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicioAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pCalendario.setBackground(new java.awt.Color(255, 255, 255));
        pCalendario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 4, true), "  GESTIONAR FILTROS DE EXPORTACIÓN  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(31, 87, 12))); // NOI18N
        pCalendario.setPreferredSize(new java.awt.Dimension(1366, 105));

        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCategoria.setText("Categoría");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));
        cbCategoria.setEnabled(false);

        lblDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDivision.setText("División");

        cbDivision.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));
        cbDivision.setEnabled(false);
        cbDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisionActionPerformed(evt);
            }
        });

        lblJornada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblJornada.setText("Jornada");

        cbJornada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));
        cbJornada.setEnabled(false);

        lblFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaInicio.setText("Fecha de Incio");

        txtFechaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaInicio.setEnabled(false);
        txtFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaInicioActionPerformed(evt);
            }
        });

        lblFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFechaFin.setText("Fecha de Fin");

        txtFechaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFechaFin.setEnabled(false);
        txtFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaFinActionPerformed(evt);
            }
        });

        btnFiltroEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnFiltroEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltroEditar.setText("Editar Filtros");
        btnFiltroEditar.setFocusPainted(false);
        btnFiltroEditar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnFiltroEditar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnFiltroEditar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnFiltroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroEditarActionPerformed(evt);
            }
        });

        btnFiltroAceptar.setBackground(new java.awt.Color(31, 87, 12));
        btnFiltroAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltroAceptar.setText("Aceptar");
        btnFiltroAceptar.setMaximumSize(new java.awt.Dimension(120, 23));
        btnFiltroAceptar.setMinimumSize(new java.awt.Dimension(120, 23));
        btnFiltroAceptar.setName(""); // NOI18N
        btnFiltroAceptar.setPreferredSize(new java.awt.Dimension(120, 23));
        btnFiltroAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCalendarioLayout = new javax.swing.GroupLayout(pCalendario);
        pCalendario.setLayout(pCalendarioLayout);
        pCalendarioLayout.setHorizontalGroup(
            pCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCalendarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDivision)
                .addGap(18, 18, 18)
                .addComponent(cbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblJornada)
                .addGap(18, 18, 18)
                .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaInicio)
                .addGap(18, 18, 18)
                .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFechaFin)
                .addGap(18, 18, 18)
                .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnFiltroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFiltroAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pCalendarioLayout.setVerticalGroup(
            pCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivision)
                    .addComponent(cbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJornada)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFin)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltroAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tCalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jornada", "Fecha", "Día", "Hora", "Equipo Local", "Equipo Visitante", "Campo", "Competición", "Partido aplazado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCalendario.setEnabled(false);
        tCalendario.getTableHeader().setReorderingAllowed(false);
        scrollCalendario.setViewportView(tCalendario);

        btnCalendarioEditar.setBackground(new java.awt.Color(31, 87, 12));
        btnCalendarioEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendarioEditar.setText("Editar Calendario");
        btnCalendarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioEditarActionPerformed(evt);
            }
        });

        btnCalendarioGenerar.setBackground(new java.awt.Color(31, 87, 12));
        btnCalendarioGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendarioGenerar.setText("Guardar Calendario");
        btnCalendarioGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioGenerarActionPerformed(evt);
            }
        });

        btnCalendarioSalir.setBackground(new java.awt.Color(31, 87, 12));
        btnCalendarioSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendarioSalir.setText("Salir");
        btnCalendarioSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioSalirActionPerformed(evt);
            }
        });

        mbCalendario.setBackground(new java.awt.Color(31, 87, 12));
        mbCalendario.setForeground(new java.awt.Color(255, 255, 255));

        mExportar.setForeground(new java.awt.Color(255, 255, 255));
        mExportar.setText("Exportar Calendario");
        mExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mExportarActionPerformed(evt);
            }
        });

        miExcel.setBackground(new java.awt.Color(31, 87, 12));
        miExcel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miExcel.setForeground(new java.awt.Color(255, 255, 255));
        miExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/excel.png"))); // NOI18N
        miExcel.setText("Exportar como Excel");
        miExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExcelActionPerformed(evt);
            }
        });
        mExportar.add(miExcel);

        miPDF.setBackground(new java.awt.Color(31, 87, 12));
        miPDF.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miPDF.setForeground(new java.awt.Color(255, 255, 255));
        miPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pdf.png"))); // NOI18N
        miPDF.setText("Exportar como PDF");
        miPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPDFActionPerformed(evt);
            }
        });
        mExportar.add(miPDF);

        mbCalendario.add(mExportar);

        setJMenuBar(mbCalendario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalendarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalendarioGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalendarioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollCalendario)
                    .addComponent(pCalendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                    .addComponent(jInicioCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInicioCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalendarioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalendarioGenerar)
                    .addComponent(btnCalendarioEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalendarioGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioGenerarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/guardar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios realizados en el calendario?", "Guardar cambios", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                
        }      
        
    }//GEN-LAST:event_btnCalendarioGenerarActionPerformed

    private void mExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mExportarActionPerformed

    private void miExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExcelActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Excel (*.xls; *.xlsx)", "xls", "xlsx");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showSaveDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File fichero = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fichero.getAbsolutePath());
            //aqui debe coger los datos de la BBDD y guardarlos en un excel

        }
//        String categoria2 = (String) cbCategoria.getSelectedItem();
//        String division2 = (String) cbDivision.getSelectedItem();
//        String jornada2 = (String) cbJornada.getSelectedItem();
//        
//        switch(categoria2) {
//            
//          case "Todas": 
//            switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioTODAS.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//            
//        case "Senior": 
//            switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioSenior.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//        case "Veteranos+30": 
//                switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+30.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        case "Veteranos+35": 
//            switch(division2){
//                case "Primera":
//                  switch(jornada2){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+35.xlsx");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        }  
    }//GEN-LAST:event_miExcelActionPerformed

    private void miPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPDFActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo PDF (*.pdf)", "pdf");
        fileChooser.setFileFilter(filter);
        int seleccion = fileChooser.showSaveDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File fichero = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fichero.getAbsolutePath());
            //aqui debe coger los datos de la BBDD y guardarlos en un PDF

        }
//        String categoria = (String) cbCategoria.getSelectedItem();
//        String division = (String) cbDivision.getSelectedItem();
//        String jornada = (String) cbJornada.getSelectedItem();
//        
//        switch(categoria) {
//            
//        case "Todas": 
//            switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioTODAS.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//            
//        case "Senior": 
//            switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioSenior.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                        ex.printStackTrace();
//                   }
//            }
//            }
//            break;
//        case "Veteranos+30": 
//                switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+30.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        case "Veteranos+35": 
//            switch(division){
//                case "Primera":
//                  switch(jornada){
//                    case "1": 
//                        try {
//                        File path = new File ("src\\calendarios\\EjemploCalendarioVet+35.pdf");
//                        Desktop.getDesktop().open(path);
//                   }catch (IOException ex) {
//                    }
//            }
//            }
//            break;
//        }
    }//GEN-LAST:event_miPDFActionPerformed

    private void txtInicioFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioFechaInicioActionPerformed

    private void txtInicioFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInicioFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicioFechaFinActionPerformed

    private void btnIniciocEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciocEditarActionPerformed

            txtInicioFechaInicio.setEnabled(true);
            txtInicioFechaFin.setEnabled(true);
            
    }//GEN-LAST:event_btnIniciocEditarActionPerformed

    private void btnFiltroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroEditarActionPerformed

            cbCategoria.setEnabled(true);
            cbDivision.setEnabled(true);
            cbJornada.setEnabled(true);
            txtFechaInicio.setEnabled(true);
            txtFechaFin.setEnabled(true);

    }//GEN-LAST:event_btnFiltroEditarActionPerformed

    private void btnFiltroAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroAceptarActionPerformed

              filtro = new Filtros(this.cbCategoria.getSelectedIndex(), this.cbDivision.getSelectedIndex(),
              this.cbJornada.getSelectedIndex(), this.tCalendario);

    }//GEN-LAST:event_btnFiltroAceptarActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void cbDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDivisionActionPerformed

    private void btnInicioAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioAplicarActionPerformed

            gc.generaFechas(this.txtInicioFechaInicio.getText(), this.txtInicioFechaFin.getText(), this.tCalendario);

    }//GEN-LAST:event_btnInicioAplicarActionPerformed

    private void btnCalendarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioEditarActionPerformed
        ImageIcon icon = new ImageIcon("src/resources/editar.png");
        int input = JOptionPane.showConfirmDialog(null, "¿Desea editar los datos del calendario?", "Editar datos del calendario", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
            tCalendario.setEnabled(true);
        }
    }//GEN-LAST:event_btnCalendarioEditarActionPerformed

    private void btnCalendarioSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioSalirActionPerformed
        close();            
    }//GEN-LAST:event_btnCalendarioSalirActionPerformed
    
    public void close() {
             dispose();             
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendarioEditar;
    private javax.swing.JButton btnCalendarioGenerar;
    private javax.swing.JButton btnCalendarioSalir;
    private javax.swing.JButton btnFiltroAceptar;
    private javax.swing.JButton btnFiltroEditar;
    private javax.swing.JButton btnInicioAplicar;
    private javax.swing.JButton btnIniciocEditar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbDivision;
    private javax.swing.JComboBox<String> cbJornada;
    private javax.swing.JPanel jInicioCalendario;
    private javax.swing.JLabel lbInicioFechaInicio;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDivision;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblInicioFechaFin;
    private javax.swing.JLabel lblJornada;
    private javax.swing.JMenu mExportar;
    private javax.swing.JMenuBar mbCalendario;
    private javax.swing.JMenuItem miExcel;
    private javax.swing.JMenuItem miPDF;
    private javax.swing.JPanel pCalendario;
    private javax.swing.JScrollPane scrollCalendario;
    private javax.swing.JTable tCalendario;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtInicioFechaFin;
    private javax.swing.JTextField txtInicioFechaInicio;
    // End of variables declaration//GEN-END:variables
}
