/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;

/**
 *
 * @author rob_a
 */
public class EditarCampo extends javax.swing.JDialog {

    /**
     * Creates new form EditarCampo
     */
    public EditarCampo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(232, 245, 228));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditarCampo = new javax.swing.JLabel();
        cbEditarCampo = new javax.swing.JComboBox<>();
        btnEditarCampo = new javax.swing.JButton();
        btnEliminarCampo = new javax.swing.JButton();
        btnCancelarCampo = new javax.swing.JButton();
        lblLogoEditarCampo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar campo");
        setBackground(new java.awt.Color(31, 87, 12));

        lblEditarCampo.setBackground(new java.awt.Color(31, 87, 12));
        lblEditarCampo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblEditarCampo.setForeground(new java.awt.Color(31, 87, 12));
        lblEditarCampo.setText("Seleccione un campo");

        cbEditarCampo.setBackground(new java.awt.Color(31, 87, 12));
        cbEditarCampo.setForeground(new java.awt.Color(255, 255, 255));
        cbEditarCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEditarCampo.setBackground(new java.awt.Color(31, 87, 12));
        btnEditarCampo.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCampo.setText("Editar");
        btnEditarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCampoActionPerformed(evt);
            }
        });

        btnEliminarCampo.setBackground(new java.awt.Color(31, 87, 12));
        btnEliminarCampo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCampo.setText("Eliminar");
        btnEliminarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCampoActionPerformed(evt);
            }
        });

        btnCancelarCampo.setBackground(new java.awt.Color(31, 87, 12));
        btnCancelarCampo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCampo.setText("Cancelar");
        btnCancelarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCampoActionPerformed(evt);
            }
        });

        lblLogoEditarCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/campo_menu.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEditarCampo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogoEditarCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditarCampo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addComponent(btnEditarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogoEditarCampo)
                    .addComponent(lblEditarCampo))
                .addGap(18, 18, 18)
                .addComponent(cbEditarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCampo)
                    .addComponent(btnEliminarCampo)
                    .addComponent(btnEditarCampo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCampoActionPerformed
        cbEditarCampo.setEditable(true);
    }//GEN-LAST:event_btnEditarCampoActionPerformed

    private void btnEliminarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCampoActionPerformed

    private void btnCancelarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCampoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarCampo dialog = new EditarCampo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarCampo;
    private javax.swing.JButton btnEditarCampo;
    private javax.swing.JButton btnEliminarCampo;
    private javax.swing.JComboBox<String> cbEditarCampo;
    private javax.swing.JLabel lblEditarCampo;
    private javax.swing.JLabel lblLogoEditarCampo;
    // End of variables declaration//GEN-END:variables
}
