/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import sources.GestionarDivisiones;
import sources.MostrarDatos;

/**
 *
 * @author rob_a
 */
public class EditarDivision extends javax.swing.JDialog {
    private final MostrarDatos md = new MostrarDatos();
    private final GestionarDivisiones gd = new GestionarDivisiones();
    private String divisionAnterior = null;
    /**
     * Creates new form EditarDivision
     */
    public EditarDivision(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(232, 245, 228));
        
        md.llenarComboDivisiones(this.cbEditarDivision);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditarDivision = new javax.swing.JLabel();
        cbEditarDivision = new javax.swing.JComboBox<>();
        btnEditarDivision = new javax.swing.JButton();
        btnEliminarDivision = new javax.swing.JButton();
        btnCancelarDivision = new javax.swing.JButton();
        lblLogoEditarDivision = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar división");
        setBackground(new java.awt.Color(31, 87, 12));

        lblEditarDivision.setBackground(new java.awt.Color(31, 87, 12));
        lblEditarDivision.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        lblEditarDivision.setForeground(new java.awt.Color(31, 87, 12));
        lblEditarDivision.setText("Seleccione una división");

        cbEditarDivision.setBackground(new java.awt.Color(31, 87, 12));
        cbEditarDivision.setForeground(new java.awt.Color(255, 255, 255));
        cbEditarDivision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una división" }));

        btnEditarDivision.setBackground(new java.awt.Color(31, 87, 12));
        btnEditarDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDivision.setText("Editar");
        btnEditarDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDivisionActionPerformed(evt);
            }
        });

        btnEliminarDivision.setBackground(new java.awt.Color(31, 87, 12));
        btnEliminarDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDivision.setText("Eliminar");
        btnEliminarDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDivisionActionPerformed(evt);
            }
        });

        btnCancelarDivision.setBackground(new java.awt.Color(31, 87, 12));
        btnCancelarDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarDivision.setText("Cancelar");
        btnCancelarDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDivisionActionPerformed(evt);
            }
        });

        lblLogoEditarDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/division.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbEditarDivision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogoEditarDivision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEditarDivision)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogoEditarDivision)
                    .addComponent(lblEditarDivision))
                .addGap(18, 18, 18)
                .addComponent(cbEditarDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarDivision)
                    .addComponent(btnEliminarDivision)
                    .addComponent(btnEditarDivision))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDivisionActionPerformed
        cbEditarDivision.setEditable(true);

        if(btnEditarDivision.getText().equals("Editar")){
            divisionAnterior = this.cbEditarDivision.getSelectedItem().toString();
        }else{
            gd.editarDivision(divisionAnterior, this.cbEditarDivision.getSelectedItem().toString());
            dispose();
        }
        btnEditarDivision.setText("Aceptar");
    }//GEN-LAST:event_btnEditarDivisionActionPerformed

    private void btnEliminarDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDivisionActionPerformed
        gd.eliminarDivision(this.cbEditarDivision.getSelectedIndex());
        dispose();
    }//GEN-LAST:event_btnEliminarDivisionActionPerformed

    private void btnCancelarDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDivisionActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDivision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarDivision dialog = new EditarDivision(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarDivision;
    private javax.swing.JButton btnEditarDivision;
    private javax.swing.JButton btnEliminarDivision;
    private javax.swing.JComboBox<String> cbEditarDivision;
    private javax.swing.JLabel lblEditarDivision;
    private javax.swing.JLabel lblLogoEditarDivision;
    // End of variables declaration//GEN-END:variables
}
