/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sources.GestionarBBDD;
import sources.GestionarCampeonato;
import sources.GestionarCampos;
import sources.GestionarCategorias;
import sources.GestionarDivisiones;
import sources.GestionarEquipos;
import sources.LeerExcel;

/**
 *
 * @author rob_a
 */
public class Principal extends javax.swing.JFrame {
    
    private final GestionarCampeonato gcp = new GestionarCampeonato ();
    private final GestionarCampos gc = new GestionarCampos();
    private final GestionarCategorias gct = new GestionarCategorias();
    private final GestionarDivisiones gd = new GestionarDivisiones ();
    private final GestionarEquipos ge = new GestionarEquipos ();

private FondoPrincipal fondo;
    /**
     * Creates new form Panel
     */
    public Principal() {

        initComponents();


    
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/logo1.png"));
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(450, 450, Image.SCALE_DEFAULT));
        
        lblLogoPrincipal.setText(null);
        lblLogoPrincipal.setIcon( icono );
        
        Image iconMenu = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo1.png"));
        setIconImage(iconMenu);
        
        
        fondo = new FondoPrincipal();
        this.add(fondo);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
   
        });
        
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e){
                  int x, y;
                  x = Principal.this.getWidth();
                  y = Principal.this.getHeight();

                  fondo.fondoZize(x, y);
            }
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoPrincipal = new javax.swing.JLabel();
        btncalendarioP = new javax.swing.JButton();
        btnEquiposP = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        mbprincipal = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miNuevaJornada = new javax.swing.JMenuItem();
        miCambiarLogo = new javax.swing.JMenuItem();
        miAcerca = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSalir = new javax.swing.JMenuItem();
        mGestion = new javax.swing.JMenu();
        mImportarPrincipal = new javax.swing.JMenu();
        miImportarCampos = new javax.swing.JMenuItem();
        miImportarEquipos = new javax.swing.JMenuItem();
        mAgregarPrincipal = new javax.swing.JMenu();
        miAgregarCampos = new javax.swing.JMenuItem();
        miAgregarCategoria = new javax.swing.JMenuItem();
        miAgregarDivision = new javax.swing.JMenuItem();
        miAgregarEquipos = new javax.swing.JMenuItem();
        mEditarPrincipal = new javax.swing.JMenu();
        miEditarCampos = new javax.swing.JMenuItem();
        miEditarCategoria = new javax.swing.JMenuItem();
        miEditarDivision = new javax.swing.JMenuItem();
        miEditarEquipos = new javax.swing.JMenuItem();
        mBBDD = new javax.swing.JMenu();
        mVaciarBBDD = new javax.swing.JMenu();
        miVaciarCalendario = new javax.swing.JMenuItem();
        miVaciarCampos = new javax.swing.JMenuItem();
        miVaciarCategoria = new javax.swing.JMenuItem();
        mivaciarDivision = new javax.swing.JMenuItem();
        mivaciarEquipos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Partidos");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        lblLogoPrincipal.setMaximumSize(new java.awt.Dimension(450, 450));
        lblLogoPrincipal.setMinimumSize(new java.awt.Dimension(450, 450));
        lblLogoPrincipal.setPreferredSize(new java.awt.Dimension(450, 450));

        btncalendarioP.setBackground(new java.awt.Color(31, 87, 12));
        btncalendarioP.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        btncalendarioP.setForeground(new java.awt.Color(255, 255, 255));
        btncalendarioP.setText("GESTIONAR CALENDARIO");
        btncalendarioP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncalendarioP.setFocusPainted(false);
        btncalendarioP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncalendarioPMouseEntered(evt);
            }
        });
        btncalendarioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalendarioPActionPerformed(evt);
            }
        });

        btnEquiposP.setBackground(new java.awt.Color(31, 87, 12));
        btnEquiposP.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        btnEquiposP.setForeground(new java.awt.Color(255, 255, 255));
        btnEquiposP.setText("CONFIGURACIÓN");
        btnEquiposP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquiposPActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(31, 87, 12));
        btnSalir.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 48)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        mbprincipal.setBackground(new java.awt.Color(31, 87, 12));
        mbprincipal.setForeground(new java.awt.Color(255, 255, 255));

        mArchivo.setForeground(new java.awt.Color(255, 255, 255));
        mArchivo.setText("Archivo");

        miNuevaJornada.setBackground(new java.awt.Color(31, 87, 12));
        miNuevaJornada.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miNuevaJornada.setForeground(new java.awt.Color(255, 255, 255));
        miNuevaJornada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new.png"))); // NOI18N
        miNuevaJornada.setText(" Nueva Temporada");
        miNuevaJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevaJornadaActionPerformed(evt);
            }
        });
        mArchivo.add(miNuevaJornada);

        miCambiarLogo.setBackground(new java.awt.Color(31, 87, 12));
        miCambiarLogo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miCambiarLogo.setForeground(new java.awt.Color(255, 255, 255));
        miCambiarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cambiarlogo.png"))); // NOI18N
        miCambiarLogo.setText(" Cambiar Logo");
        miCambiarLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCambiarLogoActionPerformed(evt);
            }
        });
        mArchivo.add(miCambiarLogo);

        miAcerca.setBackground(new java.awt.Color(31, 87, 12));
        miAcerca.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miAcerca.setForeground(new java.awt.Color(255, 255, 255));
        miAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/info.png"))); // NOI18N
        miAcerca.setText(" Acerca...");
        miAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaActionPerformed(evt);
            }
        });
        mArchivo.add(miAcerca);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        mArchivo.add(jSeparator1);

        miSalir.setBackground(new java.awt.Color(31, 87, 12));
        miSalir.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miSalir.setForeground(new java.awt.Color(255, 255, 255));
        miSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir2.png"))); // NOI18N
        miSalir.setText(" Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        mbprincipal.add(mArchivo);

        mGestion.setBackground(new java.awt.Color(31, 87, 12));
        mGestion.setForeground(new java.awt.Color(255, 255, 255));
        mGestion.setText("Gestión");

        mImportarPrincipal.setBackground(new java.awt.Color(31, 87, 12));
        mImportarPrincipal.setForeground(new java.awt.Color(31, 87, 12));
        mImportarPrincipal.setText("Importar");

        miImportarCampos.setBackground(new java.awt.Color(31, 87, 12));
        miImportarCampos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miImportarCampos.setForeground(new java.awt.Color(255, 255, 255));
        miImportarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/campo_menu.png"))); // NOI18N
        miImportarCampos.setText(" Campos");
        miImportarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportarCamposActionPerformed(evt);
            }
        });
        mImportarPrincipal.add(miImportarCampos);

        miImportarEquipos.setBackground(new java.awt.Color(31, 87, 12));
        miImportarEquipos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miImportarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        miImportarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/equipos_menu.png"))); // NOI18N
        miImportarEquipos.setText(" Equipos");
        miImportarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportarEquiposActionPerformed(evt);
            }
        });
        mImportarPrincipal.add(miImportarEquipos);

        mGestion.add(mImportarPrincipal);

        mAgregarPrincipal.setBackground(new java.awt.Color(31, 87, 12));
        mAgregarPrincipal.setForeground(new java.awt.Color(31, 87, 12));
        mAgregarPrincipal.setText("Agregar");

        miAgregarCampos.setBackground(new java.awt.Color(31, 87, 12));
        miAgregarCampos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miAgregarCampos.setForeground(new java.awt.Color(255, 255, 255));
        miAgregarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/campo_menu.png"))); // NOI18N
        miAgregarCampos.setText(" Campo");
        miAgregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarCamposActionPerformed(evt);
            }
        });
        mAgregarPrincipal.add(miAgregarCampos);

        miAgregarCategoria.setBackground(new java.awt.Color(31, 87, 12));
        miAgregarCategoria.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miAgregarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        miAgregarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/competicion.png"))); // NOI18N
        miAgregarCategoria.setText(" Categoría");
        miAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarCategoriaActionPerformed(evt);
            }
        });
        mAgregarPrincipal.add(miAgregarCategoria);

        miAgregarDivision.setBackground(new java.awt.Color(31, 87, 12));
        miAgregarDivision.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miAgregarDivision.setForeground(new java.awt.Color(255, 255, 255));
        miAgregarDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/division.png"))); // NOI18N
        miAgregarDivision.setText(" División");
        miAgregarDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarDivisionActionPerformed(evt);
            }
        });
        mAgregarPrincipal.add(miAgregarDivision);

        miAgregarEquipos.setBackground(new java.awt.Color(31, 87, 12));
        miAgregarEquipos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miAgregarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        miAgregarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/equipos_menu.png"))); // NOI18N
        miAgregarEquipos.setText(" Equipo");
        miAgregarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarEquiposActionPerformed(evt);
            }
        });
        mAgregarPrincipal.add(miAgregarEquipos);

        mGestion.add(mAgregarPrincipal);

        mEditarPrincipal.setText("Editar");

        miEditarCampos.setBackground(new java.awt.Color(31, 87, 12));
        miEditarCampos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miEditarCampos.setForeground(new java.awt.Color(255, 255, 255));
        miEditarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/campo_menu.png"))); // NOI18N
        miEditarCampos.setText(" Campo");
        miEditarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarCamposActionPerformed(evt);
            }
        });
        mEditarPrincipal.add(miEditarCampos);

        miEditarCategoria.setBackground(new java.awt.Color(31, 87, 12));
        miEditarCategoria.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miEditarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        miEditarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/competicion.png"))); // NOI18N
        miEditarCategoria.setText("Categoría");
        miEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarCategoriaActionPerformed(evt);
            }
        });
        mEditarPrincipal.add(miEditarCategoria);

        miEditarDivision.setBackground(new java.awt.Color(31, 87, 12));
        miEditarDivision.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miEditarDivision.setForeground(new java.awt.Color(255, 255, 255));
        miEditarDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/division.png"))); // NOI18N
        miEditarDivision.setText(" División");
        miEditarDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarDivisionActionPerformed(evt);
            }
        });
        mEditarPrincipal.add(miEditarDivision);

        miEditarEquipos.setBackground(new java.awt.Color(31, 87, 12));
        miEditarEquipos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miEditarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        miEditarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/equipos_menu.png"))); // NOI18N
        miEditarEquipos.setText(" Equipo");
        miEditarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarEquiposActionPerformed(evt);
            }
        });
        mEditarPrincipal.add(miEditarEquipos);

        mGestion.add(mEditarPrincipal);

        mbprincipal.add(mGestion);

        mBBDD.setBackground(new java.awt.Color(31, 87, 12));
        mBBDD.setForeground(new java.awt.Color(255, 255, 255));
        mBBDD.setText("BBDD");

        mVaciarBBDD.setForeground(new java.awt.Color(31, 87, 12));
        mVaciarBBDD.setText("Vaciar");

        miVaciarCalendario.setBackground(new java.awt.Color(31, 87, 12));
        miVaciarCalendario.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miVaciarCalendario.setForeground(new java.awt.Color(255, 255, 255));
        miVaciarCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calendario.png"))); // NOI18N
        miVaciarCalendario.setText(" Calendario");
        miVaciarCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVaciarCalendarioActionPerformed(evt);
            }
        });
        mVaciarBBDD.add(miVaciarCalendario);

        miVaciarCampos.setBackground(new java.awt.Color(31, 87, 12));
        miVaciarCampos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miVaciarCampos.setForeground(new java.awt.Color(255, 255, 255));
        miVaciarCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/campo_menu.png"))); // NOI18N
        miVaciarCampos.setText(" Campos");
        miVaciarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVaciarCamposActionPerformed(evt);
            }
        });
        mVaciarBBDD.add(miVaciarCampos);

        miVaciarCategoria.setBackground(new java.awt.Color(31, 87, 12));
        miVaciarCategoria.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        miVaciarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        miVaciarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/competicion.png"))); // NOI18N
        miVaciarCategoria.setText(" Categoría");
        miVaciarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVaciarCategoriaActionPerformed(evt);
            }
        });
        mVaciarBBDD.add(miVaciarCategoria);

        mivaciarDivision.setBackground(new java.awt.Color(31, 87, 12));
        mivaciarDivision.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        mivaciarDivision.setForeground(new java.awt.Color(255, 255, 255));
        mivaciarDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/division.png"))); // NOI18N
        mivaciarDivision.setText(" División");
        mivaciarDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivaciarDivisionActionPerformed(evt);
            }
        });
        mVaciarBBDD.add(mivaciarDivision);

        mivaciarEquipos.setBackground(new java.awt.Color(31, 87, 12));
        mivaciarEquipos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        mivaciarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        mivaciarEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/equipos_menu.png"))); // NOI18N
        mivaciarEquipos.setText(" Equipos");
        mivaciarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivaciarEquiposActionPerformed(evt);
            }
        });
        mVaciarBBDD.add(mivaciarEquipos);

        mBBDD.add(mVaciarBBDD);

        mbprincipal.add(mBBDD);

        setJMenuBar(mbprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogoPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEquiposP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncalendarioP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblLogoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncalendarioP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnEquiposP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEquiposPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposPActionPerformed
        Restricciones frm = new Restricciones ();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEquiposPActionPerformed

    private void btncalendarioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalendarioPActionPerformed
        Calendario frm = new Calendario ();
        frm.setVisible(true);
    }//GEN-LAST:event_btncalendarioPActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
            close();                   
    }//GEN-LAST:event_btnSalirActionPerformed

    private void miCambiarLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCambiarLogoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = fileChooser.getSelectedFile();
            File destino = new File ("src\\resources\\logo1.png");
            try{

                if(!destino.exists()) {
                    destino.createNewFile();
                }
                FileChannel entrada = null;
                FileChannel salida = null;
                try {
                    entrada = new FileInputStream(fichero).getChannel();
                    salida = new FileOutputStream(destino).getChannel();
                    salida.transferFrom(entrada,0, entrada.size());
                    ImageIcon icon = new ImageIcon(destino.toString());
                    Icon icono = new ImageIcon(icon.getImage().getScaledInstance(450, 450, Image.SCALE_DEFAULT));
                    lblLogoPrincipal.setText(null);
                    lblLogoPrincipal.setIcon( icono );
                    Image iconMenu = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo1.png"));
                    setIconImage(iconMenu);
                }
                finally {
                    if(entrada != null) {
                        entrada.close();
                    }
                    if(salida != null) {
                        salida.close();
                    }
                }
            }catch(
                Exception ex){
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);
            }
        }
    }//GEN-LAST:event_miCambiarLogoActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange

    }//GEN-LAST:event_formPropertyChange

    private void btncalendarioPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncalendarioPMouseEntered

    }//GEN-LAST:event_btncalendarioPMouseEntered

    private void miImportarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportarCamposActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Excel (*.xlsx)",  "xlsx");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File fichero = fileChooser.getSelectedFile();
            //Desktop.getDesktop().open(fichero);
            //aqui debe coger los datos del excel y cargarlos a la BBDD
            new Thread(new LeerExcel(fichero)).start();

        }
    }//GEN-LAST:event_miImportarCamposActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        close(); 
    }//GEN-LAST:event_miSalirActionPerformed

    private void miAgregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarCamposActionPerformed
        new AgregarCampo(this, true).setVisible(true);           
    }//GEN-LAST:event_miAgregarCamposActionPerformed

    private void miVaciarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVaciarCamposActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/warning.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea eliminar todos los campos de la BBDD ?", "Eliminar campos", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                int confir = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea realizar esta acción?\nEste cambio no se puede deshacer ", "Advertencia de seguridad",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
                if (confir == JOptionPane.YES_OPTION) {
                    gc.vaciarCampo();
                }
        } 
    }//GEN-LAST:event_miVaciarCamposActionPerformed

    private void miImportarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportarEquiposActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Excel (*.xlsx)", "xlsx");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(new Principal());
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            File fichero = fileChooser.getSelectedFile();
            //Desktop.getDesktop().open(fichero);
            //aqui debe coger los datos del excel y cargarlos a la BBDD
            new Thread(new LeerExcel(fichero)).start();

        }
    }//GEN-LAST:event_miImportarEquiposActionPerformed

    private void miAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarCategoriaActionPerformed
        new AgregarCategoria(this, true).setVisible(true);
    }//GEN-LAST:event_miAgregarCategoriaActionPerformed

    private void miAgregarDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarDivisionActionPerformed
        new AgregarDivision(this, true).setVisible(true);
    }//GEN-LAST:event_miAgregarDivisionActionPerformed

    private void miAgregarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarEquiposActionPerformed
        new AgregarEquipo(this, true).setVisible(true);
    }//GEN-LAST:event_miAgregarEquiposActionPerformed

    private void miVaciarCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVaciarCalendarioActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/warning.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el calendario de la BBDD ?", "Eliminar calendario", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                int confir = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea realizar esta acción?\nEste cambio no se puede deshacer ", "Advertencia de seguridad",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
                if (confir == JOptionPane.YES_OPTION) {
                    gcp.vaciarCampeonato();
                }
        }  
    }//GEN-LAST:event_miVaciarCalendarioActionPerformed

    private void miVaciarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVaciarCategoriaActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/warning.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea eliminar todas las categorías de la BBDD ?", "Eliminar competiciones", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                int confir = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea realizar esta acción?\nEste cambio no se puede deshacer ", "Advertencia de seguridad", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
                if (confir == JOptionPane.YES_OPTION) {
                    gct.vaciarCategoria();
                }
        }  
    }//GEN-LAST:event_miVaciarCategoriaActionPerformed

    private void mivaciarDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivaciarDivisionActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/warning.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea eliminar todas las divisiones de la BBDD ?", "Eliminar divisiones", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                int confir = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea realizar esta acción?\nEste cambio no se puede deshacer ", "Advertencia de seguridad", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
                if (confir == JOptionPane.YES_OPTION) {
                    gd.vaciarDivision();
                }
        }  
    }//GEN-LAST:event_mivaciarDivisionActionPerformed

    private void mivaciarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivaciarEquiposActionPerformed
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/warning.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea eliminar todos los equipos de la BBDD ?", "Eliminar equipos", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (input == JOptionPane.YES_OPTION) {
                int confir = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea realizar esta acción?\nEste cambio no se puede deshacer ", "Advertencia de seguridad", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
                if (confir == JOptionPane.YES_OPTION) {
                    ge.vaciarEquipo();
                }
        } 
    }//GEN-LAST:event_mivaciarEquiposActionPerformed

    private void miAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaActionPerformed
        new Acerca(this, true).setVisible(true);
    }//GEN-LAST:event_miAcercaActionPerformed

    private void miEditarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarCamposActionPerformed
        new EditarCampo(this, true).setVisible(true);
    }//GEN-LAST:event_miEditarCamposActionPerformed

    private void miEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarCategoriaActionPerformed
        new EditarCategoria(this, true).setVisible(true);
    }//GEN-LAST:event_miEditarCategoriaActionPerformed

    private void miEditarDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarDivisionActionPerformed
        new EditarDivision(this, true).setVisible(true);
    }//GEN-LAST:event_miEditarDivisionActionPerformed

    private void miEditarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarEquiposActionPerformed
        new EditarEquipo(this, true).setVisible(true);
    }//GEN-LAST:event_miEditarEquiposActionPerformed

    private void miNuevaJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevaJornadaActionPerformed
        Object temporada = JOptionPane.showInputDialog(null, "Temporada", "Agregar temporada", JOptionPane.QUESTION_MESSAGE); 
        if(temporada != null){
            String nTemporada= temporada.toString();
            GestionarBBDD gbd = new GestionarBBDD();
            gbd.nuevaTemporada(nTemporada);
        }
    }//GEN-LAST:event_miNuevaJornadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void close() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/exit.png"));
        int input = JOptionPane.showConfirmDialog(null, "¿Desea salir de la aplicación?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
            if (input == JOptionPane.YES_OPTION) {
             System.exit(0);             
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquiposP;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btncalendarioP;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblLogoPrincipal;
    private javax.swing.JMenu mAgregarPrincipal;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mBBDD;
    private javax.swing.JMenu mEditarPrincipal;
    private javax.swing.JMenu mGestion;
    private javax.swing.JMenu mImportarPrincipal;
    private javax.swing.JMenu mVaciarBBDD;
    private javax.swing.JMenuBar mbprincipal;
    private javax.swing.JMenuItem miAcerca;
    private javax.swing.JMenuItem miAgregarCampos;
    private javax.swing.JMenuItem miAgregarCategoria;
    private javax.swing.JMenuItem miAgregarDivision;
    private javax.swing.JMenuItem miAgregarEquipos;
    private javax.swing.JMenuItem miCambiarLogo;
    private javax.swing.JMenuItem miEditarCampos;
    private javax.swing.JMenuItem miEditarCategoria;
    private javax.swing.JMenuItem miEditarDivision;
    private javax.swing.JMenuItem miEditarEquipos;
    private javax.swing.JMenuItem miImportarCampos;
    private javax.swing.JMenuItem miImportarEquipos;
    private javax.swing.JMenuItem miNuevaJornada;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miVaciarCalendario;
    private javax.swing.JMenuItem miVaciarCampos;
    private javax.swing.JMenuItem miVaciarCategoria;
    private javax.swing.JMenuItem mivaciarDivision;
    private javax.swing.JMenuItem mivaciarEquipos;
    // End of variables declaration//GEN-END:variables
}
